EMAILHOST: localhost
EMAILPORT: 587
EMAILUSER: "mulingealexmuli@gmail.com"
EMAILPASSWORD: "iizqdvpqpyoipxpn"
BROKERURL: amqp://localhost
QUEUENAME: mail_queue
TOPIC: mail_topic
ROUTINGKEY: mail_key
MONGOURI: mongodb://root:password@mongodb:27017/?maxPoolSize=20&w=majority
