EMAILHOST: localhost
EMAILPORT: 1025
EMAILUSER: ""
EMAILPASSWORD: ""
BROKERURL: amqp://localhost
QUEUENAME: mail_queue
TOPIC: mail_topic
ROUTINGKEY: mail_key
MONGOURI: mongodb://root:password@localhost:27017/?maxPoolSize=20&w=majority
